import Shirt from "./images/shirt.png";

// Database contains 22 items
const database = [
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 18999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 18999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    },
    {
        "product-id": 10000,
        "product-image": Shirt,
        "product-name": "Peach Blazer Men",
        "product-type": "Blazer",
        "product-current-price": 12999,
        "product-size": ["XS", "M", "L", "XL"],
        "product-colors": ["Black", "Maroon", "Yellow"],
        "release-date": "01-06-2022",
        "product-rating": 4.9,
        "product-sales": 999,
        "product-mrp": 24999
    }
]

export default database;